// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvxbkqdeyrhuumjtwgzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2eGJrcWRleXJodXVtanR3Z3ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NTMwNTgsImV4cCI6MjA2NTQyOTA1OH0.Ky4cXry3260kGpWFDfLhqjj4WTeFDIW6VgYCdXKn3yw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);